# SPDX-FileCopyrightText: © 2024 The "Whiteprints template context" contributors <whiteprints@pm.me>
#
# SPDX-License-Identifier: MIT

[version]
source = "vcs"

[metadata.hooks.fancy-pypi-readme]
content-type = "text/markdown"

[[metadata.hooks.fancy-pypi-readme.fragments]]
path = "README.md"

[build.targets.sdist]
only-include = [
    "src/whiteprints_template_context",
]

[build.targets.wheel]
packages = [
    "src/whiteprints_template_context",
]
only-packages = true
artifacts = [
    "**/*.mo",
]
exclude = [
    "**/*.po",
    "**/*.pot",
]

[build.hooks.custom]
dependencies = [
    "hatch-vcs>=0.4.0",
    "hatch-fancy-pypi-readme",
    "babel>=1.25.0",
    "setuptools>=2.16.0",
    "typing-extensions>=4.12.1; python_version<'3.12'",
]
