# SPDX-FileCopyrightText: © 2024 The "Whiteprints template context" contributors <whiteprints@pm.me>
#
# SPDX-License-Identifier: MIT

name: Publish container

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9].post'
      - 'v[0-9]+.[0-9]+.[0-9].post[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9].post.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-alpha'
      - 'v[0-9]+.[0-9]+.[0-9]+-alpha[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-alpha[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-beta'
      - 'v[0-9]+.[0-9]+.[0-9]+-beta[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-beta[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-pre-alpha'
      - 'v[0-9]+.[0-9]+.[0-9]+-pre-alpha[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-pre-alpha.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-pre-alpha[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-planning'
      - 'v[0-9]+.[0-9]+.[0-9]+-planning[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-planning.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-planning[0-9]+.[0-9]+'

jobs:
  container-deploy:
    name: Build and Push Container
    permissions:
      contents: read
      packages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: "${{ (contains(github.ref, '-alpha') || contains(github.ref, '-beta') || contains(github.ref, '-pre-alpha') || contains(github.ref, '-planning')) && 'publish_testghcr' || 'publish_ghcr' }}"
    env:
      REGISTRY: ghcr.io
    strategy:
      matrix:
        image:
          - name: alpine
          - name: debian
    steps:
      - name: Check out the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@5964de0df58d5ad28b04d8fe2e6b80ad47105b91 # v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3
      - name: Set up Docker Metadata
        id: docker-meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          flavor: |
            latest=auto
            prefix=
            suffix=-${{ matrix.image.base }}
          tags: |
            type=pep440,pattern={{ version }},event=tag
            type=ref,event=tag
            type=sha
      - name: Log in to the Container registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set BUILD_DATE
        run: echo "BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV
      - name: Build and Push Container
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6
        id: build-and-push
        with:
          context: .
          file: ./container/Containerfile.${{ matrix.image.name }}
          tags: |
            ${{ steps.docker-meta.outputs.tags }}
          annotations: ${{ steps.docker-meta.outputs.annotations }}
          build-args: |
            VERSION=${{ steps.docker-meta.outputs.version }}
            REVISION=${{ github.sha }}
            BUILD_DATE=${{ env.BUILD_DATE }}
          push: true
          cache-from: type=local,src=~/.docker/buildx-cache
          cache-to: type=local,dest=~/.docker/buildx-cache
      - name: Install cosign
        uses: sigstore/cosign-installer@d7d6bc7722e3daa8354c50bcb52f4837da5e9b6a # v3
      - name: Sign the images with GitHub OIDC Token
        env:
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
          TAGS: ${{ steps.docker-meta.outputs.tags }}
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes ${images}
