# SPDX-FileCopyrightText: © 2024 The "Whiteprints template context" contributors <whiteprints@pm.me>
#
# SPDX-License-Identifier: MIT

name: "Lint Pull Request"

on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    environment:
      name: tests
    permissions:
      pull-requests: read
      statuses: write
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        name: Semantic Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          wip: true
