# SPDX-FileCopyrightText: © 2024 The "Whiteprints template context" contributors <whiteprints@pm.me>
#
# SPDX-License-Identifier: MIT

name: Tests
on:
  workflow_dispatch:
  push:
    branches: ["main"]
    tags-ignore: ["**"]
  pull_request:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: tox env ${{ matrix.tox_env }}
    runs-on: ubuntu-latest
    environment:
      name: tests
    strategy:
      matrix:
        tox_env:
          - pre-commit
          - lint
          - check-types
          - check-vulnerabilities
          - check-exceptions
          - check-code-maintainability
    steps:
      - name: Check out the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install uv
        uses: astral-sh/setup-uv@887a942a15af3a7626099df99e897a18d9e5ab3a # v5
        with:
          version: "latest"
          enable-cache: true
      - name: Run the test suite
        run: |
          uvx --quiet --no-progress --with tox-uv tox run -e ${{ matrix.tox_env }}
  distribute:
    name: tox env ${{ matrix.tox_env }}
    runs-on: ubuntu-latest
    environment:
      name: tests
    strategy:
      matrix:
        tox_env:
          - distribute
    steps:
      - name: Check out the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install uv
        uses: astral-sh/setup-uv@887a942a15af3a7626099df99e897a18d9e5ab3a # v5
        with:
          version: "latest"
          enable-cache: true
      - name: Run the test suite
        run: |
          uvx --quiet --no-progress --with tox-uv tox run -e ${{ matrix.tox_env }}
      - name: Upload documentation
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4
        with:
          name: ${{ matrix.tox_env }}
          path: dist/
          overwrite: true
  documentation:
    name: tox env ${{ matrix.tox_env }}
    runs-on: ubuntu-latest
    environment:
      name: tests
    strategy:
      matrix:
        tox_env:
          - check-documentation-links
          - build-documentation
    steps:
      - name: Check out the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install uv
        uses: astral-sh/setup-uv@887a942a15af3a7626099df99e897a18d9e5ab3a # v5
        with:
          version: "latest"
          enable-cache: true
      - name: Run the test suite
        run: |
          uvx --quiet --no-progress --with tox-uv tox run -e ${{ matrix.tox_env }}
      - name: Upload documentation
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4
        with:
          name: ${{ matrix.tox_env }}
          path: docs_build/
          overwrite: true
  test:
    name: Run tests under Python ${{ matrix.python }} on ${{ matrix.os }}
    needs: check
    runs-on: ${{ matrix.os }}
    environment:
      name: tests
    strategy:
      matrix:
        python:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install uv
        uses: astral-sh/setup-uv@887a942a15af3a7626099df99e897a18d9e5ab3a # v5
        with:
          version: "latest"
          enable-cache: true
      - name: Pick environment to run
        run: |
          import os;
          env = "TOXENV=py{}{}-test\n".format(*"${{ matrix.python }}".split("."))
          with open(os.environ["GITHUB_ENV"], mode="a", encoding="utf-8") as file_handler:
              file_handler.write(env)
        shell: python
      - name: Run the test suite
        shell: bash
        run: |
          echo "REPORT_FILE=.tox/test_report.md" >> "$GITHUB_ENV"
          uvx --quiet --no-progress --with tox-uv tox run
      - name: Output reports to the job summary when tests fail
        if: failure()
        shell: bash
        run: |
          if [ -f "$REPORT_FILE" ]; then
            echo "<details><summary>Failed Test Report</summary>" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            cat "$REPORT_FILE" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "</details>" >> $GITHUB_STEP_SUMMARY
          fi
      - name: Upload coverage data
        if: always()
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4
        with:
          name: coverage-data-${{ matrix.os }}-${{ matrix.python }}
          path: .tox/.coverage.*
          overwrite: true
          include-hidden-files: true
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4
        with:
          name: test-results-${{ matrix.os }}-${{ matrix.python }}
          path: .tox/junit.*
          overwrite: true
          include-hidden-files: true
  container-deploy:
    name: Build Container
    runs-on: ubuntu-latest
    environment:
      name: tests
    env:
      REGISTRY: ghcr.io
    strategy:
      matrix:
        image:
          - name: alpine
          - name: debian
    steps:
      - name: Check out the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3
      - name: Set up Docker Metadata
        id: meta
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=pep440,pattern={{version}},event=tag
            type=ref,event=branch,prefix=latest-
            type=sha
      - name: Log in to the Container registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set BUILD_DATE
        run: echo "BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV
      - name: Build
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6
        with:
          context: .
          file: ./container/Containerfile.${{ matrix.image.name }}
          tags: |
            ${{ steps.meta.outputs.tags }}-${{ matrix.image.base }}
          annotations: ${{ steps.meta.outputs.annotations }}
          build-args: |
            VERSION=${{ steps.meta.outputs.version }}
            REVISION=${{ github.sha }}
            BUILD_DATE=${{ env.BUILD_DATE }}
          cache-from: type=local,src=~/.docker/buildx-cache
          cache-to: type=local,dest=~/.docker/buildx-cache
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: coverage
    needs:
      - test
      - container-deploy
      - documentation
      - distribute
    steps:
      - name: Check out the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install uv
        uses: astral-sh/setup-uv@887a942a15af3a7626099df99e897a18d9e5ab3a # v5
        with:
          version: "latest"
          enable-cache: true
      - name: Download coverage data
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        with:
          pattern: coverage-data-*
          merge-multiple: true
          path: .tox/
      - name: Run coverage
        run: |
          uvx --quiet --no-progress --with tox-uv tox run -e coverage-combine
          uvx --quiet --no-progress --with tox-uv tox run -e coverage-report
          uvx --quiet --no-progress --with tox-uv tox run -e coverage
          uvx --quiet --no-progress --with tox-uv tox run --quiet --quiet -e coverage -- --format=markdown >> $GITHUB_STEP_SUMMARY
      - name: Upload coverage report to CodeCov
        if: always()
        uses: codecov/codecov-action@1e68e06f1dbfde0e4cefc87efeba9e4643565303 # v5
        with:
          name: codecov-umbrella
          verbose: true
          flags: pytest
          file: .tox/.coverage.xml
          use_oidc: true
